NeedleInsertionRobot:
  ros__parameters:
    axis:
      x:
        speed:        2.5
        acceleration: 1.5
        deceleration: 1.5
        kP:            54
        kI:             4
        kD:           480
      y:
        speed:        2.5
        acceleration: 1.5
        deceleration: 1.5
        kP:            15
        kI:             4
        kD:           332
      z:
        speed:        2.5
        acceleration: 1.5
        deceleration: 1.5
        kP:            54
        kI:             4
        kD:           480
      linear_stage:
        speed:        4.0
        acceleration: 0.2289
        deceleration: 0.2289
        kP:            54
        kI:             4
        kD:           480

/stage:
  NeedleInsertionRobot:
    ros__parameters:
      axis:
        x:
          speed:        2.5
          acceleration: 1.5
          deceleration: 1.5
          kP:            54
          kI:             4
          kD:           480
        y:
          speed:        2.5
          acceleration: 1.5
          deceleration: 1.5
          kP:            15
          kI:             4
          kD:           332
        z:
          speed:        2.5
          acceleration: 1.5
          deceleration: 1.5
          kP:            54
          kI:             4
          kD:           480
        linear_stage:
          speed:        2.0
          acceleration: 0.2289
          deceleration: 0.2289
          kP:            54
          kI:             4
          kD:           480

/**:
  ros__parameters:
    axis:
      x:
        speed:        2.5
        acceleration: 1.5
        deceleration: 1.5
        kP:            54
        kI:             4
        kD:           480
      y:
        speed:        2.5
        acceleration: 1.5
        deceleration: 1.5
        kP:            15
        kI:             4
        kD:           332
      z:
        speed:        2.5
        acceleration: 1.5
        deceleration: 1.5
        kP:            54
        kI:             4
        kD:           480
      linear_stage:
        speed:        1.0
        acceleration: 0.2289
        deceleration: 0.2289
        kP:            54
        kI:             4
        kD:           480